$ANSIBLE_VAULT;1.1;AES256
38666336656433303964616237643737386130316635646234636361356163366538336366396366
3937396465346630353435663437373464666465313034310a376266633934376136316236306131
34613364646564633638323662373936326533613035623463333164303162393030393834353233
3337376433346431640a623763336665623633303264656263353434613235333636356132633363
66343932313030303566666338373933373361373039306237316431336238323031343662613139
61363130353034356463653865383063353964633564373666323335653437373739356234353466
343061613133633937646136333264346361
