multiverse:
  hosts:
    zendikar:
      ansible_host: 192.168.194.84
      ansible_user: planeswalker
      ansible_ssh_private_key_file: ~/.ssh/homelab
    dominaria:
      ansible_host: 192.168.194.168
      ansible_user: planeswalker
      ansible_ssh_private_key_file: ~/.ssh/homelab
    innistrad:
      ansible_host: 192.168.194.174
      ansible_user: planeswalker
      ansible_ssh_private_key_file: ~/.ssh/homelab

control_plane:
  hosts:
    zendikar:
    dominaria:
    innistrad:

workers:
  hosts:
    zendikar:
    dominaria:
    innistrad:

all:
  vars:
    miniconda_prefix: /opt/miniconda3
    conda_env_name: ansible
    conda_python_version: "3.13"
    miniconda_url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    ansible_python_interpreter: "{{ miniconda_prefix }}/envs/{{ conda_env_name }}/bin/python"
    k8s_major_minor: "1.34"
    k8s_version: "1.34.2-1.1"
    cni_plugins_version: "1.8.0"
    cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz"
    pod_network_cidr: "10.244.0.0/16"
    service_cidr: "10.96.0.0/12"
    flux_github_owner: "your-github-username"
    flux_github_repo: "homelab-ansible-flux"
    flux_github_branch: "main"
    flux_github_path: "./clusters/kubernetes"